version: '3.4'

services:
  beassesment:
    image: beassesment
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      NODE_PORT: 3000
      MONGO_URL: mongodb://mongodb:27017/beassesment
      
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app

  mongodb:
    image: mongo:latest
    ports:
      - 27019:27017
    volumes:
      - ./data:/data/db

volumes:
  data: {}
  beassesment: {}
